services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: listacompras
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/listacompras
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "19000:19000"  # túnel / metro
      - "19001:19001"  # LAN
      - "19002:19002"  # DevTools
      - "19006:19006"  # Web
      - "8081:8081"
    environment:
      EXPO_NO_INTERACTIVE: "1"
      EXPO_DEVTOOLS_LISTEN_ADDRESS: "0.0.0.0"
    depends_on:
      - backend

volumes:
  postgres_data:
