version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: listacompras
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile       # crie um Dockerfile lรก
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/listacompras
      SPRING_DATASOURCE_USERNAME: seu_usuario
      SPRING_DATASOURCE_PASSWORD: sua_senha

volumes:
  postgres_data:
